### ISSUE TITLE
Additional sensors

### ISSUE THREAD

**Issue by haadmina** [ITTV-tools/homeassistant-kostalplenticore#14]
Hello,

According the MODBUS manual from Kostal, there are some more addresses available. Is it possible, to integrate some of them as well ? 

56: Inverter state 
122: Power limit from EVU
???: Power to grid  (Einspeisung in Watt) ? If there is no such address, is it possible to calculate it and allocate it to a sensor ? 

That would be great.

Thank you
 Markus

**Comment by SaSa1983** [comment]
This extension does not work via the MODBUS Protocol.
It uses the Rest API that is also used by the Web-Interface of the Inverter

**Comment by ITTV-tools** [comment]
Hello,
I added LimitEvuAbs (Power limit from EVU)
Kostal power grid sensor shows how much is sold

**Comment by ITTV-tools** [comment]
Also InverterState
