### ISSUE TITLE
PV3 missing

### ISSUE THREAD

**Issue by SaSa1983** [ITTV-tools/homeassistant-kostalplenticore#15]
The Costal Plenticore Plus Models have 3 inputs (pv1, pv2, pv3) whereas the 3rd one _may_ be used for battery instead of input. Bit in my case I use all 3 ports for solar input (3-MPPT). Is there by chance a way to get the 3rd one?

Essentially the following monitored options are missing:

PV3Power
PV3Voltage
PV3Current

There should also be an option in your configuration which decides how to handle PV3. 
(Parallel to host/password)
Sth. like "_battery_on_pv3_: true/false" 

(The default value should be false, since it requires a license activation to enable PV3 for battery within the Plenticore)

Your PVPower calculation should then be changed to: 
"PVPower": ["pv1+2+3", "P", "Kostal pv power", POWER_WATT, "mdi:solar-power"],

Whereas the calculation should look like

if self.moduleid == "pv1+2+3":
            try:
                pv1 = int(
                    self.api.getProcessdata("devices:local:pv1", [self.id])[0]["value"]
                )
            except:
                pv1 = "error"
            try:
                pv2 = int(
                    self.api.getProcessdata("devices:local:pv2", [self.id])[0]["value"]
                )
            except:
                pv2 = "error"
            try:
                pv3 = int(
                    self.api.getProcessdata("devices:local:pv3", [self.id])[0]["value"]
                )
            except:
                pv3 = _battery_on_pv3_ ? 0 : "error"
            if(pv1 != "error" and pv2 != "error" and pv3 != "error"):
                value = pv1 + pv2 +pv3
            else:
                value= "error"

Feel free to contact me in case of any question.

Kind regards

Sascha Sander

**Comment by SaSa1983** [comment]
For clarification here's an image from my inverters web interface.
Note that it is currently powered off, thus there's just voltage on the PV Incoming side but now power
![image](https://user-images.githubusercontent.com/1494844/108184178-31dbcf00-710b-11eb-884d-36dd7abb6b42.png)

**Comment by ITTV-tools** [comment]
I updated the code it works with two inputs. Can you try if it works with 3 ? 
Add this to your config:
DC_Inputs: 3
monitored_conditions:
        - PV3Power
        - PV3Voltage
        - PV3Current

**Comment by SaSa1983** [comment]
In your current master state there're merge conflicts within the sensors.py

ITTV-tools <notifications@github.com> schrieb am Di., 23. Feb. 2021, 14:45:

**Comment by ITTV-tools** [comment]
fixed

**Comment by SaSa1983** [comment]
see: https://github.com/ITTV-tools/homeassistant-kostalplenticore/pull/17

This is checked with 1, 2 or 3 string (dc_inputs).

**Comment by ITTV-tools** [comment]
Now I have to add async and setup with [configration flows](https://developers.home-assistant.io/docs/config_entries_options_flow_handler). That would be nice.

Do you maybe have any experience with this ? Because I dont really get it.

**Comment by SaSa1983** [comment]
I could take a look into it. Despite it would be nice to add the
configuration via ui rather than the configuration file and to support
reconnect attempt rather than needing to restart HA

ITTV-tools <notifications@github.com> schrieb am Mi., 24. Feb. 2021, 11:35:
