### ISSUE TITLE
Error while setting up kostal_plenticore

### ISSUE THREAD

**Issue by molelightn** [ITTV-tools/homeassistant-kostalplenticore#2]
Hi there,

would you be so kind an help me with this.

- installed via HACS
- setup yaml conf to:

```
- platform: kostal_plenticore
    host: 192.168.1.xxx
    password: xxxxxxxx
    monitored_conditions:
      - BatteryPercent
      - BatteryCycles
      - BatteryPower
      - HomeGridPower
      - HomeOwnPower
      - HomePVPower
      - HomeBatteryPower
      - GridPower
      - PVPower
      - AutarkyDay
      - AutarkyMonth
      - AutarkyTotal
      - AutarkyYear
      - CO2SavingDay
      - CO2SavingMonth
      - CO2SavingTotal
      - CO2SavingYear
```

and received following:

```
2020-03-22 11:59:58 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up kostal_plenticore platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kostal_plenticore/sensor.py", line 158, in setup_platform
    SENSOR_TYPES[sensor][4],
  File "/config/custom_components/kostal_plenticore/sensor.py", line 175, in __init__
    self._state = int(self.api.getProcessdata(self.moduleid, [self.id])[0]["value"])
IndexError: list index out of range
2020-03-22 12:00:09 WARNING (MainThread) [homeassistant.setup] Setup of default_config is taking over 10 seconds.
```

Any help appreciated.

br

**Comment by ITTV-tools** [comment]
Please try the newest version (just released).
Use the new config.

**Comment by molelightn** [comment]
running on 0.3.2 now with

```
  - platform: kostal_plenticore
    host: 192.168.1.xxx
    password: xxxxxxxx
    monitored_conditions:
      - BatteryPercent
      - BatteryCycles
      - BatteryPower
      - HomeGridPower
      - HomeOwnPower
      - HomePVPower
      - HomeBatteryPower
      - GridPower
      - DCPower
      - AutarkyDay
      - AutarkyMonth
      - AutarkyTotal
      - AutarkyYear
      - CO2SavingDay
      - CO2SavingMonth
      - CO2SavingTotal
      - CO2SavingYear
      - PV1Power
      - PV1Voltage
      - PV1Current
      - PV2Power
      - PV2Voltage
      - PV2Current
```
but error looks almost the same : (  

```
2020-03-22 21:27:01 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up kostal_plenticore platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/kostal_plenticore/sensor.py", line 188, in setup_platform
    SENSOR_TYPES[sensor][4],
  File "/config/custom_components/kostal_plenticore/sensor.py", line 205, in __init__
    self._state = int(self.api.getProcessdata(self.moduleid, [self.id])[0]["value"])
IndexError: list index out of range
```

Could it be in relation with firmware running on my Plenticore? 

Name Kostal5
Typenbezeichnung PLENTICORE plus 5.5
UI-Version 01.04.02090
MC-Version 01.16
IOC-Version 01.16
HW-Version 1
Ländereinstellung Austria TD4 NSR
Batterieeingang gesperrt

**Comment by ITTV-tools** [comment]
Looks like you have no Battery.
Try removing:
      - BatteryPercent
      - BatteryCycles
      - BatteryPower
      - HomeBatteryPower
Your firmware is older then mine. But I have also Plenticore plus 7.0
You can try to download the newest firmware on the kostal page.

**Comment by molelightn** [comment]
Good morning, 

yes battery is not unlocked yet. Got it basically to work with following config:

```
  - platform: kostal_plenticore
    host: 192.168.1.xxx
    password: xxxxxxxx
    monitored_conditions:
      - HomeGridPower
      - HomeOwnPower
      - HomePVPower
      - CO2SavingDay
      - CO2SavingMonth
      - CO2SavingTotal
      - CO2SavingYear
      - PV1Power
      - PV1Voltage
      - PV1Current
      - PV2Power
      - PV2Voltage
      - PV2Current
```

The first 3 Home/Own/PV -Power show 0 all the time.

Co2 values are all fine, PV1+2 Power and Voltage same, only current would be nice to show up in mA. It readings only start while current is >1. 

Will try to update firmware today, may the power readings show up afterwards.

Thanks for this great project and your help

br

Edit:

Inverter running on latest available Firmware now, readings like above kept the same.

br

**Comment by ITTV-tools** [comment]
I add the request for mA to my todo.

**Comment by molelightn** [comment]
3 coffees went out to you 👍 

If you further work on this project:

- in 0.3.2 you renamed PVPower to DCPower 
- in 0,4.0 PVPower (sum of PV1+2) was added -> not working as it need to be DCPower as you wrote in 0.3.2

-Current in mA is on todo  👍 
-AC values would be nice too, (Current, Voltage, PowerFactor, Power,  Power Sum, DigitalInputs)

Thank you for your work :)

**Comment by ITTV-tools** [comment]
Thank you very much.

DCPower still exists. It shows all DC Power that goes though the inverter. 
First I thought that is the PV Power, because it looks the same at daytime.

"The new PVPower" shows now the real power generation of the PV.
If you have no battery, there is probably no difference.

I will try to add you requested sensors.

**Comment by snitkjaer** [comment]
I ran into the same issue (I also do not have a battery). Fixed by removing:
- BatteryPercent
- BatteryCycles
- BatteryPower
- HomeBatteryPower

PLENTICORE plus 10
FW: 01.42
