### ISSUE TITLE
PV gross yield

### ISSUE THREAD

**Issue by habitoti** [ITTV-tools/homeassistant-kostalplenticore#21]
Hi,
it seems that the daily PV yield is not the actual gross panel yield at any given point, but only minus what went into the battery so far. So it seems I have no figure to provide the daily yield after sunset, and if the battery lasts over midnight I can also not precisely read that figure for the day. I could do some approx. computation from SoC and known total capacity, but this would just be an estimation then. On the other hand, the standard Kostal app does show such a figure. Not sure whether they do such kind of a computation or whether there is a „gross yield“ figure available from the inverter, which you just don‘t expose? 
Thanks, habitoti

**Comment by ITTV-tools** [comment]
This integration is not longer maintained, Please use the official integration
