### ISSUE TITLE
Problem when connected to 2 kostal Plenticore Inverters

### ISSUE THREAD

**Issue by Irming1109** [ITTV-tools/homeassistant-kostalplenticore#24]
Hi. I have a setup where i connect to two different Kostal Plenticore Inverters. As such - it works just fint. But it seems to mix up the data from the inverters upon restart of the Home Assistant Server. Some values then suddenly change places from one inverter to the other. For instance the value of "sensor.kostal_home_power_from_battery_2" and "sensor.kostal_home_power_from_battery" switch places. If what im writing makes no sense - please ask me for clarification.

**Comment by ITTV-tools** [comment]
Somebody made a new integration Ha 2021.5. I guess it will work better.

**Comment by Irming1109** [comment]
How do i find this new integration. Nothing comes up on searching ?

**Comment by ITTV-tools** [comment]
Its not released yet. Release Date is 5th of may https://rc.home-assistant.io/blog/
