### ISSUE TITLE
Integration not working anymore after HA update to 2021.8.4

### ISSUE THREAD

**Issue by mdino-gh** [ITTV-tools/homeassistant-kostalplenticore#26]
Hello,

I know that this integration is no longer maintained. Meanwhile Home Assistant has an own integration for Kostal Plenticore inverter. Check out https://www.home-assistant.io/integrations/kostal_plenticore/.

Nevertheless since I am assuming that the name of all related entities will change I am not ready to move the HA integration yet.

To get this integration working again with HA 2021.8.x version the following changes in the file const.py of the integration are required:

Change all occurences of ELECTRICAL_CURRENT_AMPERE to ELECTRIC_CURRENT_AMPERE
Change all occurences of VOLT to ELECTRIC_POTENTIAL_VOLT

Restart Home Assistant and it should work again

```
$ diff const.py /etc/homeassistant/custom_components/kostal_plenticore/const.py
9,10c9,10
<     ELECTRICAL_CURRENT_AMPERE,
<     VOLT,
---
>     ELECTRIC_CURRENT_AMPERE,
>     ELECTRIC_POTENTIAL_VOLT,
86c86
<         VOLT,
---
>         ELECTRIC_POTENTIAL_VOLT,
93c93
<         ELECTRICAL_CURRENT_AMPERE,
---
>         ELECTRIC_CURRENT_AMPERE,
317c317
<         ELECTRICAL_CURRENT_AMPERE,
---
>         ELECTRIC_CURRENT_AMPERE,
331c331
<         VOLT,
---
>         ELECTRIC_POTENTIAL_VOLT,
338c338
<         ELECTRICAL_CURRENT_AMPERE,
---
>         ELECTRIC_CURRENT_AMPERE,
352c352
<         VOLT,
---
>         ELECTRIC_POTENTIAL_VOLT,
359c359
<         ELECTRICAL_CURRENT_AMPERE,
---
>         ELECTRIC_CURRENT_AMPERE,
373c373
<         VOLT,
---
>         ELECTRIC_POTENTIAL_VOLT,
474c474
<         VOLT,
---
>         ELECTRIC_POTENTIAL_VOLT,
481c481
<         ELECTRICAL_CURRENT_AMPERE,
---
>         ELECTRIC_CURRENT_AMPERE,
498c498
<         VOLT,
---
>         ELECTRIC_POTENTIAL_VOLT,
505c505
<         ELECTRICAL_CURRENT_AMPERE,
---
>         ELECTRIC_CURRENT_AMPERE,
```

Best Regards

Matthias

PS: It seem that one is able to edit the const.py in this repository, but I am not an experienced enough user to create a new release (if this would be possible at all)

**Comment by dome227** [comment]
Hi together, 

unfortunately I have the same problem after upgrading to home assistant v2021.8. 

`"Platform error sensor.kostal_plenticore - cannot import name 'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)"`

Using the integration until 2021.7, I really loved this integration. 

It was nice to check out the statistics in lovelace and to track the data via grafana. 

Would there be any opportunity to make it compatible and to use it with new energy features in 2021.8 ? :) 

Using comments in const.py is not a solution. Like Matthias I am not that experienced to solve it on my own. 

Thanks a lot in advance! 

Best Regards,

Dominik

**Comment by bagges** [comment]
I created a pull request but the readme states: NOT LONGER MAINTAINED

**Comment by ITTV-tools** [comment]
I merged it
