### ISSUE TITLE
Can the integration still used instead of the integrated one in HA?

### ISSUE THREAD

**Issue by Tscherno** [ITTV-tools/homeassistant-kostalplenticore#28]
I've seen that you just published a new version (hopefully as compatibility for the Energy section). Can i still use that custom integration in favor of the ingrated one?

**Comment by ITTV-tools** [comment]
Hi,
no I just merged #27 a pull request, so it works with 2021.8.
I use the integrated one my self. The code is just better. Whats wrong with it ?

**Comment by Tscherno** [comment]
I don't get the energy values for the new Energy section from Kostal.

**Comment by ITTV-tools** [comment]
In the official integration it is already updated but not released yet. You can download the code https://github.com/home-assistant/core/tree/dev/homeassistant/components/kostal_plenticore
Place it in you custom_components folder. 
Edit manifest.json 
add blow name: 
"version": "1.1.1",

Then it should work :) 
Do not forget to delete it before the next update.
