### ISSUE TITLE
RQST additional sensors

### ISSUE THREAD

**Issue by Karssi** [ITTV-tools/homeassistant-kostalplenticore#3]
Hi.

Thank you for creating this integration. Makes my life a bit easier.
Would it be possible for you to add the following sensors?

- Total AC Active Power in W [register 172]. As this (I assume) is the amount of power that is available for use/feed-in (after conversion DC to AC) 
- Yield in Wh (Total, Daily, Yearly, Monthly). [register 320, 322, 324 & 326]
- Total consumption in Wh (Batt, Grid, PV, Total). [register 110, 112, 114 & 118]

Thanks,
Michiel

**Comment by ITTV-tools** [comment]
Hi Michiel,

I use the web API so the registes do not help much :) 
But should be possible if the webinterface shows the values.

Can you provide some screenshots of the webgui, so I know wich values you mean ?

Lukas

**Comment by Karssi** [comment]
Hi Lukas,

Hmm..
I would if you could help me how to use the webgui. I know how to access the webpage @ IP/api/v1 but that is about it. Sorry..

Michiel

**Comment by ITTV-tools** [comment]
I mean the normal webgui. I will search for it in the API. I just want to be sure that I know what values you mean

**Comment by Karssi** [comment]
Oh.. of course…
I thought you meant the WebAPI page 😊

Here are the values that would be nice to have…
If I understand it correctly the Inverter output is the actual amount of power available to be used (after conversion) and therefore the more interesting value to visualize (pls correct me if I’m wrong).

Thanks…

Michiel

**Comment by ITTV-tools** [comment]
![grafik](https://user-images.githubusercontent.com/29466357/80074315-41b96f80-8549-11ea-89db-59ee9017b3a0.png)
You mean those values ?

**Comment by Karssi** [comment]
Yes..



-------- Original message --------

**Comment by ITTV-tools** [comment]
I added the following sensors: 
- HomeConsumptionDay
- HomeConsumptionMonth
- HomeConsumptionTotal
- HomeConsumptionYear
- HomeConsumptionFromBatDay
- HomeConsumptionFromBatMonth
- HomeConsumptionFromBatTotal
- HomeConsumptionFromBatYear
- HomeConsumptionFromGridDay
- HomeConsumptionFromGridMonth
- HomeConsumptionFromGridTotal
- HomeConsumptionFromGridYear 
- HomeConsumptionFromPVDay
- HomeConsumptionFromPVMonth
- HomeConsumptionFromPVTotal
- HomeConsumptionFromPVYear
- HomeConsumptionYieldDay
- HomeConsumptionYieldMonth
- HomeConsumptionYieldTotal
- HomeConsumptionYieldYear

My test environment broken at the moment. You can test it by downloading and replacing the sensor.py manually with your existing one.

**Comment by Karssi** [comment]
Hi. 

Thanks.. works like a charm..
Only the unit of measurement is wrong. It show as W in stead of Wh.

Michiel

**Comment by ITTV-tools** [comment]
oh sorry, forgot to change it :) Now it should be fixed

**Comment by Karssi** [comment]
Yep.. perfect… 
Thanks..
