### ISSUE TITLE
new Sensors for Statistic + PV/DC Power

### ISSUE THREAD

**Issue by molelightn** [ITTV-tools/homeassistant-kostalplenticore#4]
Hi there ITTV,

Once again thank you for your work on this project, appreciate it.

Unfortunately the new added sensor do not work for me. As i have no Power Meter installed i do not get any consumption values from the statistic page.

The only values displayed are as found in screenshot below. I have tried all of the new sensors for consumption but none of it reply a value, always 0.

![image](https://user-images.githubusercontent.com/62118239/81147402-877b2c80-8f7a-11ea-8203-121329365a67.png)

Do you see a way to make these values available as sensor? PVProductionDay e.g.?

Another thing, 

I think i found small problem with PVPower and DCPower.
In my understanding PV Power should be the genarated Power on AC side and therefore always a little lower than DCPower.

And DCPower the summarized value of each Input (PV1Power+PV2Power)

I compared values from PV and DC Power with the one i see on Kostal GUI:

![image](https://user-images.githubusercontent.com/62118239/81147814-60712a80-8f7b-11ea-9658-6b5cd5ef4260.png)

And this is what sensors in HA report me:

![image](https://user-images.githubusercontent.com/62118239/81147923-931b2300-8f7b-11ea-986d-989101837c9e.png)

It looks PV and DC Power report the same values.

Please share your thoughts.

Thank you.

br mole

**Comment by molelightn** [comment]
Yield Values working, don't know why it took some time to take effect.

Still having problems in understanding of difference from PV/DC Power

**Comment by ITTV-tools** [comment]
Sorry for my late answer. If I remember correctly, the difference is only visible with a battery.
DC Power shows all power that is going through the inverter. So if you have a battery that is discharging and there is no sun, it will be different.
HomePVPower should be AC
