### ISSUE TITLE
platform error

### ISSUE THREAD

**Issue by kaygee60** [ITTV-tools/homeassistant-kostalplenticore#7]
This error message appears when I check the configuration: 

Platform error sensor.kostal_plenticore - cannot import name 'PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

I have looked for the specified const.py, but there is no such directory or file. What do I have to change?

**Comment by hubroski** [comment]
Did you perform the last update of Home Assistant? I've had the same error until I updated Hassio￼￼.

**Comment by kaygee60** [comment]
Thank you, that worked! I just updated to 0.115.3 – yes!

 

Von: hubroski <notifications@github.com> 
Gesendet: Sonntag, 27. September 2020 16:24
An: ITTV-tools/homeassistant-kostalplenticore <homeassistant-kostalplenticore@noreply.github.com>
Cc: kaygee60 <franz@hexxium.com>; Author <author@noreply.github.com>
Betreff: Re: [ITTV-tools/homeassistant-kostalplenticore] platform error (#7)

 

Did you perform the last update of Home Assistant? I've had the same error until I updated Hassio￼￼.
